version: '3.5'
services:
    db:
        image: 'mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04'
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '1433:1433'
